version: "3.9"

services:

  salt-master:
    container_name: "salt-master-${SALT_VERSION}"
    hostname: 'salt-master-${SALT_VERSION}'
    build:
      context: .
      dockerfile: SALT/Dockerfile.master
      args:
        SALT_VERSION: "${SALT_VERSION}"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
    volumes:
      # bind folder with master files
      - type: bind
        source: ./SALT/master/
        target: /etc/salt/   
        
  salt-minion:
    container_name: "salt-minion-${SALT_VERSION}-${PROXY_ID}"
    hostname: "salt-minion-${SALT_VERSION}-${PROXY_ID}"
    build:
      context: .
      dockerfile: SALT/Dockerfile.minion
      args:
        SALT_VERSION: "${SALT_VERSION}"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      PROXY_ID: "${PROXY_ID}"
    depends_on:
      - salt-master
    volumes:
      # bind folder with proxy minion files
      - type: bind
        source: ./SALT/proxy/
        target: /etc/salt/ 
      # bind folder with proxy minion data files        
      - type: bind
        source: ./SALT/salt_nornir_data/
        target: /var/salt-nornir/  
